var GAME_LEVELS = [
  ["xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxx                                                                          xxx",
   "xxx                                                                          xxx",
   "xxx                                                                          xxx",
   "xxx                                                                          xxx",
   "xxx @                    o                                               o   xxx",
   "xxx                                                                          xxx",
   "xxx                     fff         xxx      xxx      xxx       xxx       fffxxx",
   "xxxxxxx      fff                                                         ffffxxx",
   "xxxxx                                                                   fffffxxx",
   "xxxx      o                                                             fffffxxx",
   "xxx                         xxx                                         fffffxxx",
   "xxx                                                                     fffffxxx",
   "xxx                     fff                                       xxx   fffffxxx",
   "xxx          xxxxxx                                                     fffffxxx",
   "xxxxxxx      xxxxxxfxxx             xxxxxxxxx     o      xxxxxx         fffffxxx",
   "xxxxxxx      xx     xxx             xxxxxxxxx            xxxxxx         fffffxxx",
   "xxxxxxx      xx  o  xxx             xxxxxxxxx     x      xxxxxx         xxxxxxxx",
   "xxxxxxx!!!!!!xx     xxx!!!!!!!!!!!!!xxxxxxxxx!!!!!x!!!!!!xxxxxx!!!!!!!!!!!!!!xxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!!!!!!!xx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!!!!x",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!!xx"],
  ["xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxx                      xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxx                      ffffffffffffffffffffffffffffffffffffffffxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxx                      ffffffffffffffffffffffffffffffffffffffffxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxx                      xxxxxxxxxxxxxxxxxxxfffffffxxxxxxxxxxxfffxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxx                      xxxxxxxxxxxxxxxxxxxfffffffxxxxxxxxxxxfffxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxx    o                 xxxxxxxxxxxxxxxxxxxfffffffxxxxxxxxxxxfffxxxxxxxxxxxxxxxxxxxxxxxxxx                    xxx",
   "xxx                      xxxxxxxxxxxxxxxxxxxfffffffxxxxxxxxxxxfffxxxxxxxxxxxxxxxxxxxxxxxxxx                    xxx",
   "xxx   xxx            vxxxxxxxxxxxxxxxxxxxxxxfffffffxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                    xxx",
   "xxx                      xxxxxxxxxxxxxxxxxxxfffffffxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx          o         xxx",
   "xxx                      xxxxxxxxxxxxxxxxxxxfffffffxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                    xxx",
   "xxx                      xxxxxxxxxxxxxxxxxxx       xxx!!xx!!xx!!xx!!xxxxxxxxxxxxxxxxxxxxxxx         !!!        xxx",
   "xxx   @                  xxxxxxxxxxxxxxxxxxx                           xxxxxxxxxxxxxxxxxxxx                    xxx",
   "xxxv                  xxxxxxxxxxxxxxxxxxxxxx             o      o      xxxxxxxxxxxxxxxxxxxx                    xxx",
   "xxxxxxxxxxxxx            xxxxxxxxxxxxxxxxxxx                           xxxxxxxxxxxxxxxxxxxx                    xxx",
   "xxxxxxxxxxxxx            xxxxxxxxxxxxxxxxxxx                           xxxxxxxxxxxxxxxxxxxx                    xxx",
   "xxxxxxxxxxxxx                 |   |   |                                xv                vx                    xxx",
   "xxxxxxxxxxxxx                                                                                                  xxx",
   "xxxxxxxxxxxxxxttttttx                         ttt                                                              xxx",
   "xxxxxxxxxxxxxxxxxxxxx                                                                                          xxx",
   "xxxxxxxxxxxxxxxmmmmxx                                                                                          xxx",
   "xxxx     xxxxxxxxxxxx       |   |   |   |                                                                      xxx",
   "xxxx  o  xxxxxxxxxxxx      xxxxxxxxxxxxxxx                             xv                vx                    xxx",
   "xxxx     ffffffffffff      xxxxxxxxxxxxxxx                             xxxxxxxxxxxxxxxxxxxx                    xxx",
   "xxxx     ffffffffffff      xxxxxxxxxxxxxxx                             xxxxxxxxxxxxxxxxxxxx                    xxx",
   "xxxxxxxxxxxxxxxxxxxxxxtttxxxxxxxxxxxxxxxxxxxxxxxxxxxxxtttttttttttttttxxxxxxxxxxxxxxxxxxxxxxxxttttttttttttttttxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"],
  ["xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                                 xxx",
   "xxxxx                                         xxxxxxxxxxxxxxxxxxxxxxxxxxxx                                 xxx",
   "xxxxx   o                                     xxxxxxxxxxxxxxxxxxxxxxxxxxxx                o                xxx",
   "xxxxx                                         xxxxxxxxxxxxxxxxxxxxxxxxxxxx                                 xxx",
   "xxxxx  xxx                                    xxxxxxxxxxxxxxxxxxxxxxxxxxxx                                 xxx",
   "xxxxx                                         xxxxxxxxxxxxxxxxxxxxxxxxxxxx                                 xxx",
   "xxxxx        xxx                              xxxxxxxxxxxxxxxxxxxxxxxxxxxx                                 xxx",
   "xxxxx                                         xxxxxxxxxxxxxxxxxxxxxxxxxxxx                                 xxx",
   "xxxxx              xxx                        xxxxxxxxxxxxxxxxxxxxxxxxxxxx                                 xxx",
   "xxxxx                                         xxxxxxxxxxxxxxxxxxxxxxxxxxxx                                 xxx",
   "xxxxx                                         xxxxxxxxxxxxxxxxxxxxxxxxxxxx          ttt                    xxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxx                     xxxxxxxxxxxxxxxxxxxxxxxxxxxx                                 xxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxx                     xxxxxxxxxxxxxxxxxxxxxxxxxxxx                                 xxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxx                     xxxxxxxxxxxxxxxxxxxxxxxxxxxx                                 xxx",
   "xxxxx     xsssssssssssssx                     xssssssssssssssssssssssssssx                                 xxx",
   "xxxxx                                         v                                                  ttt       xxx",
   "xxxxx  @                                             o                   v                                 xxx",
   "xxxxx     xsssssssssssssxxxtttttxxx                                   xssx                                 xxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx           xssssssssssssssxffffffffxxxx                                 xxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx           xxxxxxxxxxxxxxxxffffffffxxxx                                 xxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx           xxxxxxxxxxxxxxxxffffffffxxxx   ttt                           xxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx           xxxxxxxxxxxxxxxxffffffffxxxx                                 xxx",
   "xxxxxxxxxxxxxxfffffffffffffffffffff           xxxxxxxxxxxxxxxxffffffffxxxx                                 xxx",
   "xxxxxxxxxxxxxxfffffffffffffffffffff           ffffffffffffffff        xxxx                                 xxx",
   "xxxxxxxxxxxxxxffoffffffffffffffffff           ffffffffffffffff       vxxxx                                 xxx",
   "xxxxxxxxxxxxxxfffffxxxxxxxxxxxxxxxx        xxxxxxssssssssssssxxxxtttxxxxxx                                 xxx",
   "xxxxxxxxxxxxxxffffxxxxxxxxxxxxxxxxx         xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                   ttt           xxx",
   "xxxxxxxxxxxxxxfffffxxxxxxxxxxxxxxxx          xxxxxxxxxxxxxxxxxxxxxxxxxxxxx                                 xxx",
   "xxxxxxxxxxxxxxfffffxxxxxxxxxxxxxxxx           xxxxxxxxxxxxxxxxxxxxxxxxxxxx                                 xxx",
   "xxxxxxxxxxxxxxfffffxxxxxxxxxxxxxxxx           xxxxxxxxxxxxxxxxxxxxxxxxxxxx                                 xxx",
   "xxxxxxxxxxxxxxxffffxxxxxxxxxxxxxxxx           xxxxxxxxxxxxxxxxxxxxxxxxxxxx                                 xxx",
   "xxxxxxxxxxxxxxfffffxxxxxxxxxxxxxxxx           xxxxxxxxxxxxxxxxxxxxxxxxxxxx                                 xxx",
   "xxxxxxxxxxxxxxfffffxxxxxxxxxxxxxxxx           xxxxxxxxxxxxxxxxxxxxxxxxxxxx       ttt                       xxx",
   "xxxxxxxxxxxxxxfffffxxxxxxxxxxxxxxxx           xxxxxxxxxxxxxxxxxxxxxxxxxxxx                                 xxx",
   "xxxxxxxxxxxxxxffffxxxxxxxxxxxxxxxxx           xxxxxxxxxxxxxxxxxxxxxxxxxxxx                                 xxx",
   "xxxxxxxxxxxxxxfffffxxxxxxxxxxxxxxxx           xxxxxxxxxxxxxxxxxxxxxxxxxxxx                                 xxx",
   "xxxxxxxxxxxxxxffffffxxxxxxxxxxxxxxx           xxxxxxxxxxxxxxxxxxxxxxxxxxxx                                 xxx",
   "xxxxxxxxxxxxxxffffffxxxxxxxxxxxxxxx           xxxxxxxxxxxxxxxxxxxxxxxxxxxx                o      ttt       xxx",
   "xxxxxxxxxxxxxxxffffffffffffffffffff           xxxxxxxxxxxxxxxxxxxxxxxxxxxx                                 xxx",
   "xxxxxxxxxxxxxxfffffffffffffffffffff           xxxxxxxxxxxxxxxxxxxxxxxxxxxx               xxx               xxx",
   "xxxxxxxxxxxxxx!!!!xxxxxxxxxxxxxxxxxxx         xxxxxxxxxxxxxxxxxxxxxxxxxxxx                                 xxx",
   "xxxxxxxxxxxxx!!!!!!xxxxxxxxxxxxxxxxxxxxttttxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxx",
   "xxxxxxxxxx!!!!!!!!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxxx",
   "xxxxxxxxxxx!!!!!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!xxxxxxxx"],
  ["xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!!!!!!!!xxxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxx                                                                                                        xxx",
   "xxx                                                                                                       xxx",
   "xxx                                                                                                        xxx",
   "xxx                                                                                                        xxx",
   "xxx                                                                                                        xxx",
   "xxx                                                                                                        xxx",
   "xxx                                                                                                        xxx",
   "xxx                                                                                                        xxx",
   "xxx                                                                                                        xxx",
   "xxx                                                                                                        xxx",
   "xxx                        x               x  x  x    x  x    x   xxxx   x                                 xxx",
   "xxx                         x             x   x  xx   x  xx   x  x    x  xxxx                              xxx",
   "xxx                          x     x     x    x  x x  x  x x  x  x    x  x   x                             xxx",
   "xxx                           x   x x   x     x  x  x x  x  x x   xxxx   x                                 xxx",
   "xxx                            x x   x x      x  x   xx  x   xx   x      x                                 xxx",
   "xxx                             x     x       x  x    x  x    x    xxx   x                                 xxx",
   "xxx                                                                                                        xxx",
   "xxx                                                                                                        xxx",
   "xxx                                                                                                        xxx",
   "xxx                                                                                                        xxx",
   "xxx                                                                                                        xxx",
   "xxx                                                                                                        xxx",
   "xxx                                                                                                        xxx",
   "xxx                                                                                                        xxx",
   "xxx                                                                                                        xxx",
   "xxx                                                 @                                                      xxx",
   "xxx                                                                                                        xxx",
   "xxx                                                                                                        xxx",
   "xxxttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttxxx",
   "xxxxmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"]
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
